import argparse
import configargparse

def get_opts():
    # parser = argparse.ArgumentParser()
    parser = configargparse.ArgumentParser()
    parser.add_argument('--config', is_config_file=True, help='config file path')
    # common args for all datasets
    parser.add_argument('--root_dir', type=str, required=True,
                        help='root directory of dataset')
    parser.add_argument('--dataset_name', type=str, default='nerf',
                        choices=['nerf', 'nsvf', 'colmap', 'nerfpp', 'rtmv', 'tnt', 'kitti', 'mega'],
                        help='which dataset to train/test')
    parser.add_argument('--split', type=str, default='train',
                        choices=['train', 'trainval'],
                        help='use which split to train')
    parser.add_argument('--downsample', type=float, default=1.0,
                        help='downsample factor (<=1.0) for the images')
    parser.add_argument('--anti_aliasing_factor', type=float, default=1.0,
                        help='Render larger images then downsample')
    parser.add_argument('--climate', type=str, default=None,
                        help='the climate of training data, generated by ClimateGAN. options:flood/smog/wildfire')

    # model parameters
    parser.add_argument('--scale', type=float, default=0.5,
                        help='scene scale (whole scene must lie in [-scale, scale]^3')
    parser.add_argument('--use_skybox', action='store_true', default=False,
                        help='whether to use skybox')
    parser.add_argument('--use_exposure', action='store_true', default=False,
                        help='whether to train in HDR-NeRF setting')
    parser.add_argument('--embed_a', action='store_true', default=False,
                        help='whether to use appearance embeddings')
    parser.add_argument('--embed_a_len', type=int, default=4,
                        help='the length of the appearance embeddings')
    parser.add_argument('--embed_msk', action='store_true', default=False,
                        help='whether to use sigma embeddings')
    # parser.add_argument('--embed_msk_len', type=int, default=64,
    #                     help='the length of the sigma embeddings')
    # parser.add_argument('--coarse_samples', type=int, default=128,
    #                     help='total number of coarse samples')
    # parser.add_argument('--fine_samples', type=int, default=128,
    #                     help='total number of fine samples')
    parser.add_argument('--samples', action="append", default=[],
                        help='List of comma separated AS total number of samples of each stage')
    parser.add_argument('--num_classes', type=int, default=7,
                        help='total number of semantic classes')
    parser.add_argument('--depth_smooth', action='store_true', default=False,
                        help='use depth-2e-2smoothing regularization')
    parser.add_argument('--depth_mono', action='store_true', default=False,
                        help='use 2D predicted depth')

    # for kitti 360 dataset
    parser.add_argument('--kitti_scene', type=str, default='seq0_1538-1601',
                        choices=['seq0_1538-1601', 'seq0_1728-1791', 'seq0_1908-1971', 'seq0_3353-3416'],
                        help='scene in kitti dataset')
    parser.add_argument('--start', type=int, default=1538,
                        help='start index of frames to train.')
    parser.add_argument('--train_frames', type=int, default=64,
                        help='total number of frames to train.')
    parser.add_argument('--center_pose', action="append", default=[],
                        help='center of poses in kitti-360 dataset')
    parser.add_argument('--val_list', action="append", default=[],
                        help='frames for val dataset')
    
    parser.add_argument('--mb_size', type=float, default=0.01,
                        help='size of metaballs.')

    # for mega-nerf dataset
    parser.add_argument('--mega_frame_start', type=int, default=753)
    parser.add_argument('--mega_frame_end',   type=int, default=846)

    # training options
    parser.add_argument('--batch_size', type=int, default=8192,
                        help='number of rays in a batch')
    parser.add_argument('--ray_sampling_strategy', type=str, default='all_images',
                        choices=['all_images', 'same_image'],
                        help='''
                        all_images: uniformly from all pixels of ALL images
                        same_image: uniformly from all pixels of a SAME image
                        ''')
    parser.add_argument('--num_epochs', type=int, default=30,
                        help='number of training epochs')
    parser.add_argument('--normal_epochs', type=int, default=20,
                        help='number of training epochs for normal distillation')
    parser.add_argument('--num_gpus', type=int, default=1,
                        help='number of gpus')
    parser.add_argument('--lr', type=float, default=1e-2,
                        help='learning rate')
    # experimental training options
    parser.add_argument('--optimize_ext', action='store_true', default=False,
                        help='whether to optimize extrinsics (experimental)')
    parser.add_argument('--random_bg', action='store_true', default=False,
                        help='''whether to train with random bg color (real dataset only)
                        to avoid objects with black color to be predicted as transparent
                        ''')
    parser.add_argument('--normal_distillation', action='store_true', default=False,
                        help='use a small mlp to learn surface normal values')

    # validation options
    parser.add_argument('--eval_lpips', action='store_true', default=False,
                        help='evaluate lpips metric (consumes more VRAM)')
    parser.add_argument('--val_only', action='store_true', default=False,
                        help='run only validation (need to provide ckpt_path)')
    parser.add_argument('--normal_distillation_only', action='store_true', default=False,
                        help='run only normal_distillation (need to provide ckpt_path)')
    parser.add_argument('--no_save_test', action='store_true', default=False,
                        help='whether to save test image and video')
    parser.add_argument('--render_path', action='store_true', default=False,
                        help='render video through camera render path')
    parser.add_argument('--render_train', action='store_true', default=False,
                        help='render video through camera render path')

    # misc
    parser.add_argument('--exp_name', type=str, default='exp',
                        help='experiment name')
    parser.add_argument('--ckpt_load', type=str, default=None,
                        help='pretrained checkpoint to load (including optimizers, etc)')
    parser.add_argument('--ckpt_save', type=str, default='checkpoint.ckpt',
                        help='pretrained checkpoint to save (including optimizers, etc)')
    
    # render
    parser.add_argument('--render_rgb', action='store_true', default=False,
                        help='render rgb series')
    parser.add_argument('--render_depth', action='store_true', default=False,
                        help='render depth series')
    parser.add_argument('--render_normal', action='store_true', default=False,
                        help='render normal series')
    parser.add_argument('--render_normal_up', action='store_true', default=False,
                        help='render upward normal+rgb series')
    parser.add_argument('--render_semantic', action='store_true', default=False,
                        help='render semantic segmentation series')
    parser.add_argument('--normal_composite', action='store_true', default=False,
                        help='render normal+rgb composition series')
    parser.add_argument('--render_points', action='store_true', default=False,
                        help='render depth points')
    parser.add_argument('--render_mask', action='store_true', default=False,
                        help='render water mask')
    parser.add_argument('--chunk_size', type=int, default=-1, 
                        help='Divide image into chunks for rendering')
    # Simulation
    parser.add_argument('--simulate', default=None, 
                        help='Simulation effect: [smog, water, snow]')
    parser.add_argument('--depth_path', help='path to depth_raw.npy')
    # Smog
    parser.add_argument('--depth_bound', type=float, default=0.9)
    parser.add_argument('--sigma', type=float, default=1.0)
    parser.add_argument('--rgb', nargs='+', type=float, default=[1.0, 1.0, 1.0])
    # water
    parser.add_argument('--water_height', type=float, default=0.0)
    parser.add_argument('--plane_path', help='path to plane parameters')
    parser.add_argument('--refraction_idx', type=float, default=1.33)
    parser.add_argument('--gf_r', type=int, default=5, help='Guided filter, filter radius')
    parser.add_argument('--gf_eps', type=float, default=0.1, help='Guided filter, regularization term')
    parser.add_argument('--wave_len', type=float, default=1.0, help='Length of wave plane')
    parser.add_argument('--wave_ampl', type=int, default=2e6, help='Amplitude constant of wave')
    # panorama
    parser.add_argument('--pano_hw', type=int, nargs='+', default=[512, 1024], help='h, w of panorama image')
    parser.add_argument('--pano_radius', type=float, default=0.1, help='Set ray origin on the sphere at (0, 0, 0) with radius')
    parser.add_argument('--v_forward', type=float, nargs='+', default=[1, 0, 0])
    parser.add_argument('--v_down',    type=float, nargs='+', default=[0, 1, 0])
    parser.add_argument('--v_right',   type=float, nargs='+', default=[0, 0, 1])
    parser.add_argument('--pano_path', help='path to panorama image')
    # glossy 
    parser.add_argument('--gl_theta', type=float, default=0.01)
    parser.add_argument('--gl_sharpness', type=float, default=1000)
    return parser.parse_args()
